# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

a1 = Article.new(title: "The Great Bear Strikes Again", excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus facilisis eros ipsum, a scelerisque nunc scelerisque sed. Nullam vitae ornare lacus. Integer ac odio tincidunt, finibus mi quis, posuere odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non lorem semper elit eleifend rutrum. Nulla eget odio leo. Pellentesque molestie elementum nulla ac posuere. Maecenas sed metus volutpat, tempus enim id, varius nunc. Phasellus at dui ac arcu vestibulum viverra. Nam vitae enim vitae turpis molestie condimentum varius in urna. Integer tortor odio, venenatis eu finibus id, fringilla nec erat. Donec velit dolor, gravida a arcu et, condimentum convallis massa. Mauris purus metus, cursus eget metus ut, cursus auctor libero. Duis a tortor metus. Pellentesque erat enim, ornare non cursus a, fringilla in magna. Aliquam blandit nibh vel quam vestibulum rutrum et et diam. Praesent consectetur dignissim viverra.

    Ut sit amet lacus ultricies, elementum nibh eget, dictum nisi. Suspendisse maximus, libero ut semper pellentesque, ligula purus accumsan ante, eu suscipit est odio volutpat diam. Fusce non ante non enim pulvinar interdum. Fusce mattis placerat arcu, at ultrices ex laoreet ut. Vestibulum eu pretium urna. Pellentesque a fringilla arcu. Mauris condimentum diam et ipsum pulvinar, non efficitur diam varius. Mauris leo ligula, placerat id ex non, venenatis cursus dui. Donec mattis, turpis non placerat rutrum, turpis tortor viverra risus, vel aliquam erat nibh et ante.
    
    Vestibulum tempor tincidunt venenatis. Maecenas lobortis sem quis enim congue, et cursus velit laoreet. Proin euismod ut nunc et tincidunt. Pellentesque convallis suscipit tortor, vitae euismod risus tincidunt in. Proin sodales leo tincidunt bibendum semper. Integer vel interdum nisl. Proin eu consectetur elit, eget pretium odio. Pellentesque et urna rutrum nisi commodo imperdiet. Donec sed pretium enim. Quisque sit amet turpis libero. Etiam convallis nibh feugiat velit accumsan, eleifend maximus justo tincidunt.", status: 'public')
a1.save

    a2 = Article.new(title: "The Boar Who Wants To Rule", excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus facilisis eros ipsum, a scelerisque nunc scelerisque sed. Nullam vitae ornare lacus. Integer ac odio tincidunt, finibus mi quis, posuere odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non lorem semper elit eleifend rutrum. Nulla eget odio leo. Pellentesque molestie elementum nulla ac posuere. Maecenas sed metus volutpat, tempus enim id, varius nunc. Phasellus at dui ac arcu vestibulum viverra. Nam vitae enim vitae turpis molestie condimentum varius in urna. Integer tortor odio, venenatis eu finibus id, fringilla nec erat. Donec velit dolor, gravida a arcu et, condimentum convallis massa. Mauris purus metus, cursus eget metus ut, cursus auctor libero. Duis a tortor metus. Pellentesque erat enim, ornare non cursus a, fringilla in magna. Aliquam blandit nibh vel quam vestibulum rutrum et et diam. Praesent consectetur dignissim viverra.

    Ut sit amet lacus ultricies, elementum nibh eget, dictum nisi. Suspendisse maximus, libero ut semper pellentesque, ligula purus accumsan ante, eu suscipit est odio volutpat diam. Fusce non ante non enim pulvinar interdum. Fusce mattis placerat arcu, at ultrices ex laoreet ut. Vestibulum eu pretium urna. Pellentesque a fringilla arcu. Mauris condimentum diam et ipsum pulvinar, non efficitur diam varius. Mauris leo ligula, placerat id ex non, venenatis cursus dui. Donec mattis, turpis non placerat rutrum, turpis tortor viverra risus, vel aliquam erat nibh et ante.
    
    Vestibulum tempor tincidunt venenatis. Maecenas lobortis sem quis enim congue, et cursus velit laoreet. Proin euismod ut nunc et tincidunt. Pellentesque convallis suscipit tortor, vitae euismod risus tincidunt in. Proin sodales leo tincidunt bibendum semper. Integer vel interdum nisl. Proin eu consectetur elit, eget pretium odio. Pellentesque et urna rutrum nisi commodo imperdiet. Donec sed pretium enim. Quisque sit amet turpis libero. Etiam convallis nibh feugiat velit accumsan, eleifend maximus justo tincidunt.", status: 'public')

a2.save

a3 = Article.new(title: "The Goat That Made An Oath", excerpt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus facilisis eros ipsum, a scelerisque nunc scelerisque sed. Nullam vitae ornare lacus. Integer ac odio tincidunt, finibus mi quis, posuere odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non lorem semper elit eleifend rutrum. Nulla eget odio leo. Pellentesque molestie elementum nulla ac posuere. Maecenas sed metus volutpat, tempus enim id, varius nunc. Phasellus at dui ac arcu vestibulum viverra. Nam vitae enim vitae turpis molestie condimentum varius in urna. Integer tortor odio, venenatis eu finibus id, fringilla nec erat. Donec velit dolor, gravida a arcu et, condimentum convallis massa. Mauris purus metus, cursus eget metus ut, cursus auctor libero. Duis a tortor metus. Pellentesque erat enim, ornare non cursus a, fringilla in magna. Aliquam blandit nibh vel quam vestibulum rutrum et et diam. Praesent consectetur dignissim viverra.

    Ut sit amet lacus ultricies, elementum nibh eget, dictum nisi. Suspendisse maximus, libero ut semper pellentesque, ligula purus accumsan ante, eu suscipit est odio volutpat diam. Fusce non ante non enim pulvinar interdum. Fusce mattis placerat arcu, at ultrices ex laoreet ut. Vestibulum eu pretium urna. Pellentesque a fringilla arcu. Mauris condimentum diam et ipsum pulvinar, non efficitur diam varius. Mauris leo ligula, placerat id ex non, venenatis cursus dui. Donec mattis, turpis non placerat rutrum, turpis tortor viverra risus, vel aliquam erat nibh et ante.
    
    Vestibulum tempor tincidunt venenatis. Maecenas lobortis sem quis enim congue, et cursus velit laoreet. Proin euismod ut nunc et tincidunt. Pellentesque convallis suscipit tortor, vitae euismod risus tincidunt in. Proin sodales leo tincidunt bibendum semper. Integer vel interdum nisl. Proin eu consectetur elit, eget pretium odio. Pellentesque et urna rutrum nisi commodo imperdiet. Donec sed pretium enim. Quisque sit amet turpis libero. Etiam convallis nibh feugiat velit accumsan, eleifend maximus justo tincidunt.", status: 'public')

a3.save

